name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 8.0.0
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_svg:
  intl: ">=0.17.0 <=2.0.0"
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test:

flutter:
  assets:
    - assets/svg/
